"""add_foreign_key_to_assessments_created_by

Revision ID: 12485645a6b4
Revises: 1d5120eb8707
Create Date: 2025-10-24 23:13:20.576549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12485645a6b4'
down_revision = '1d5120eb8707'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'assessments', 'users', ['created_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    # ### end Alembic commands ###
