"""add_foreign_key_to_observations_reported_by

Revision ID: 1d5120eb8707
Revises: 66ba3d8e141b
Create Date: 2025-10-24 23:04:46.728238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5120eb8707'
down_revision = '66ba3d8e141b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'observations', 'users', ['reported_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observations', type_='foreignkey')
    # ### end Alembic commands ###
