"""add_parents_id_column_to_students

Revision ID: 66ba3d8e141b
Revises: 9f678d9ee3dc
Create Date: 2025-10-24 22:21:59.580002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ba3d8e141b'
down_revision = '9f678d9ee3dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('parents_id', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'parents_id')
    # ### end Alembic commands ###
