"""Add activity assignments and submissions

Revision ID: add_activity_assignments
Revises: fix_risklevel_enum
Create Date: 2025-11-28 10:50:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_activity_assignments'
down_revision = 'fix_risklevel_enum'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_assignments',
    sa.Column('assignment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('activity_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('class_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('assigned_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='assignmentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('activity_submissions',
    sa.Column('submission_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('assignment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', 'OTHER', name='filetype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'VERIFIED', 'REJECTED', name='submissionstatus'), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['activity_assignments.assignment_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_submissions')
    op.drop_table('activity_assignments')
    # ### end Alembic commands ###
