"""add_submission_comments

Revision ID: d155c07ce201
Revises: 88d1fcd59a2a
Create Date: 2025-11-28 12:30:59.869993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd155c07ce201'
down_revision = '88d1fcd59a2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_comments',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['activity_submissions.submission_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.drop_column('activities', 'accessible_by_teachers')
    op.drop_column('activities', 'subcategory')
    op.drop_column('activities', 'accessible_by_counsellors')
    op.drop_column('activities', 'special_diagnosis')
    op.drop_column('activities', 'thumbnail_url')
    op.alter_column('therapist_bookings', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('webinar_registrations', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webinar_registrations', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('therapist_bookings', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('activities', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('special_diagnosis', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('accessible_by_counsellors', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('activities', sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('accessible_by_teachers', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_table('submission_comments')
    # ### end Alembic commands ###
